language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - "npm -g jasmine-node && npm install -g istanbul"
after_success:
  - "istanbul cover ./node_modules/jasmine-node/bin/jasmine-node --captureExceptions specs && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
