language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - "npm i -g jasmine-node"
after_success:
  - "./node_modules/istanbul/lib/cli.js cover jasmine-node --captureExceptions specs && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
